import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-default">
        <header>
          <nav className="flex gap-x-4">
            <Link href={"/"}>Home</Link>
            <Link href={"/product"}>Product</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
